README.md
General README cleanup, with clarification around Connection credentials.
=> docs: clarify credential requirements

npm-shrinkwrap.json
`npm audit` found a couple of vulnerabilities:
```
=== npm audit security report ===
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │ Denial of Service                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ handlebars                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ jest [dev]                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ jest > jest-cli > @jest/core > @jest/reporters >             │
│               │ istanbul-reports > handlebars …
```
=> chore(deps): upgrade packages with vulnerabilities

README.md, npm-shrinkwrap.json, package.json, src/Modules/TelnyxRTC/RTC.ts, src/TelnyxRTCClient/TelnyxRTCClient.ts
0. npm run build
1. cd examples/react
2. npm run setup && npm run storybook
2. make a call
=> feat(WEBRTC-71): Migrate deprecated methods

src/ReactNative/README.md
I added a README to package @telnyx/react-native
=> feat(WEBRTC-99) added react-native README

README.md, examples/react/package-lock.json, examples/react/package.json, src/ReactNative/README.md
I upgraded SDK example and updated README links
1. Open the README inside `root` and `src/ReactNavite`
2. Click on all links to see if it goes to the right address.
=> upgraded SDK example and updated README links

package-lock.json, package.json
Updated dependencies to remove vulnerabilities.
1. in root folder run `npm i`
2. run `npm audit` and see if return 0 vulnerabilities.
=> feat(WEBRTC-133): updated dependencies

packages/js/examples/react-audio/package-lock.json, packages/js/examples/react-video/package-lock.json, packages/js/examples/react-video/package.json, packages/react-native/examples/calling-video-app/package-lock.json, packages/react-native/examples/calling-video-app/yarn.lock
1. Run all examples and see if they go success.
=> fix(WEBRTC-180): Update vulnerabilities dependencies.

packages/js/src/Modules/Verto/BrowserSession.ts
Adds TSDOc style comment to `connect` method.
=> Document connect and disconnect methods

packages/js/src/Modules/Verto/BrowserSession.ts
1. Test the [WebDialer RTC project](https://github.com/team-telnyx/rtc-demo-2/tree/master/rtc) with `console.log(await telnyxWebRTCClient.checkPermissions(true, false));` at [App.js](https://github.com/team-telnyx/rtc-demo-2/blob/master/rtc/src/App.js)
=> Add checkPermissions typedoc comment

.github/workflows/js-ci.yml, .github/workflows/js-draft-release.yml, .github/workflows/js-test-release.yml, packages/js/package-lock.json, packages/js/package.json
Performs dry run of release based on Conventional Changelog when PR is created
See results in this PR: https://github.com/team-telnyx/webrtc/pull/61/checks?check_run_id=1420441414
=> WIP: Automate @telnyx/webrtc release

.github/workflows/publish-release.yml, packages/js/package.json, packages/react-native/package.json
Publishes package to npm on publishing the GitHub release
=> chore: Publish npm package on release

docs/Contributing.md, packages/js/README.md, packages/js/package.json, packages/react-client/README.md, packages/react-client/package-lock.json, packages/react-client/package.json, packages/react-native/package.json
Adds release-it to react-client
=> Add release-it to react-client

packages/js/README.md, packages/react-native/README.md
- change absolute paths to relative paths
1. open `js` Readme and see if the image is showing
1. open `react-native` Readme and see if the image is showing
=> chore: change absolute paths to relative paths

packages/js/examples/react-video/package-lock.json, packages/js/examples/react-video/package.json, packages/js/examples/react-video/src/App.js
- Refactor App.js from video example to support hooks and support enable/disable webcam methods
1. cd `package/js/examples/react-video`
2. run `npm i && npm start`
3. open localhost:300 on two tabs
4. make a call enabling video and another call disabling the video.
=> feat(WEBRTC-280): refactor App.js from video example

packages/js/src/Modules/Verto/BaseSession.ts
- add typedoc on and off methods 
=> feat(WEBRTC-228-229): add typedoc on and off methods

packages/js/src/Modules/Verto/BrowserSession.ts, packages/js/src/Modules/Verto/tests/Verto.test.ts, packages/js/src/Modules/Verto/util/interfaces.ts
Removes deprecated devices properties and interface.
=> Remove deprecated devices property

packages/js/src/Modules/Verto/BaseSession.ts
Follows https://github.com/team-telnyx/webrtc/pull/75 to remove properties related to token expiration.
=> Remove properties related to token expiration

packages/js/src/Modules/Verto/webrtc/BaseCall.ts
- add typedoc on the method answer
1. Navigate into `packages/js/examples/react-audio`
2. Access http://localhost:6006/?path=/story/webdialer--example
3. Provide your SIP credentials information
4. Open a softphone you can use the [web dialer](webrtc.telnyx.com/rtc/index.html)
5. Provide another SIP credentials on web dialer and make a call to SIP from step 3
6. Come back to http://localhost:6006/?path=/story/webdialer--example
7. You should see a button `Answer`, you should click to pick up the call.
=> docs(WEBRTC-244): add typedoc on the method answer

packages/js/src/Modules/Verto/webrtc/BaseCall.ts
Documents hangup method
1. Start Storybook: `cd packages/js/examples/react-audio && npm start`
2. Go to http://localhost:6006/?path=/story/webdialer--example and fill in your username, password etc.
3. Make a call and hangup. Verify call ends
=> Document hangup

packages/js/src/Modules/Verto/webrtc/BaseCall.ts
Clarifies what is meant by "audio output" in `muteAudio` and `unmuteAudio` methods.
=> Update mute/unmute audio doc

packages/react-client/README.md, packages/react-client/example/package-lock.json, packages/react-client/example/src/App.tsx, packages/react-client/example/src/VideoCall.tsx
Cleans up video example in react-client.
1. Follow instructions in [react-client to run example app](https://github.com/team-telnyx/webrtc/tree/main/packages/react-client#development)
2. Make a video call to another SIP client that you own. Verify that video calling works
=> Clean up react-client video example

packages/js/docs/ts/README.md, packages/js/docs/ts/interfaces/inotification.md, packages/js/src/Modules/Verto/services/Handler.ts, packages/js/src/Modules/Verto/util/interfaces.ts, packages/js/src/Modules/Verto/webrtc/BaseCall.ts, packages/js/src/index.ts, packages/js/src/utils/interfaces.ts, packages/js/tsconfig.json
Documents a `telnyx.notification` event.
[Preview here](https://github.com/team-telnyx/webrtc/blob/WEBRTC-293_Document_notification/packages/js/docs/ts/interfaces/inotification.md#interface-inotification)
Note: Document change required for `@apidocs` and `@internalnote` tag usage.
=> Document notifications

.github/workflows/draft-release.yml
Switches to manually creating draft releases for webrtc and react-client.
=> Manually dispatch draft release workflow

packages/js/src/Modules/Verto/webrtc/BaseCall.ts
- Add typedocs on call transfer method.
1. Read the comments on BseCall.ts
=> docs(WEBRTC-257): add typedocs on call transfer method

packages/js/src/Modules/Verto/webrtc/BaseCall.ts
Add getter for Telnyx IDs. This makes for better documentation of Telnyx IDs as well.
1. Run `react-audio` example.
2. Make a call. Verify that `call.telnyxIDs` is an object with empty values (unless making a Call Control call)
=> Add Telnyx ID getter

docs/Contributing.md
=> Update contribution guide

packages/js/src/Modules/Verto/BrowserSession.ts, packages/js/src/Modules/Verto/webrtc/BaseCall.ts, packages/js/src/TelnyxRTC.ts
Fix minor documentation issues.
=> TSDoc copy fixes

packages/js/src/Modules/Verto/BrowserSession.ts
- update documentation from remoteElement and localElement methods, remove # from ID's
=> chore(HOTFIX): update remoteElement and localElement methods, remove # from ID's

.github/workflows/publish-release.yml, packages/api-docs/get_version.js
- Updates publish workflow to check out the correct tag
- Allows manually publishing webrtc-api-docs
=> Fix prod release workflow

packages/js/README.md, packages/js/src/Modules/Verto/tests/webrtc/helpers.test.ts, packages/js/src/Modules/Verto/webrtc/helpers.ts, packages/js/src/TelnyxRTC.ts
- Update support list to IOS and Safari
1. Review README file and support table.
=> docs(WEBRTC-369): update support list to IOS and Safari

packages/js/docs/ts/classes/call.md, packages/js/src/Modules/Verto/webrtc/BaseCall.ts
=> chore(WEBRTC-538): rollback telnyxids docs

packages/js/docs/ts/classes/telnyxrtc.md, packages/js/src/TelnyxRTC.ts
- add in docs how to handle media element in Telnyx SDK
1. Run `npm run docs`
2. See if it is equal the attached image
| Desktop     |![image](https://user-images.githubusercontent.com/16343871/131672883-540a36a9-a59c-4821-bb69-2bfb49df975f.png)|
=> chore(ENGDESK-11030): add in docs how to handle media element in Telnyx SDK

README.md, packages/react-native/README.md
- add deprecated message to react native SDK
| Readme |![image](https://user-images.githubusercontent.com/16343871/132574490-c1340ae6-a94c-475e-86f2-61de6f601d73.png)|
=> chore(WEBRTC-692): add deprecated message to react native SDK

.github/workflows/draft-release.yml, .github/workflows/publish-release.yml
=> chore: enabling github action to push on main branch when release-it commit a release message

.github/workflows/draft-release.yml, .github/workflows/publish-release.yml, packages/js/package-lock.json, packages/js/package.json
=> fix(Hotfix): package.lock update and node upgrade to 14

.github/workflows/draft-release.yml
=> chore: change commit message in docs commit to follow conventional commit rules

packages/api-docs/package.json
=> chore: update commit message in api docs release message

packages/js/.prettierrc, packages/js/src/Modules/Verto/webrtc/helpers.ts
-  add stop stream after query it
=> fix(WEBRTC-747): add stop stream after query it

.github/workflows/webrtc-test-release.yml, packages/js/examples/react-audio-widgets/package-lock.json, packages/js/examples/react-video-calling-app/package-lock.json
update package.json.lock with new deps and update webrtc-test workflow server
=> chore(WEBRTC-748): update package.json.lock with new deps and update webrtc-test workflow server

packages/js/CHANGELOG.md, packages/js/package-lock.json, packages/js/package.json
=> Hotfix npm version

packages/js/examples/react-audio-widgets/package-lock.json, packages/js/examples/react-video-calling-app/package-lock.json, packages/react-client/package-lock.json
=> chore: ran npm update

packages/js/examples/react-audio-widgets/package-lock.json, packages/js/examples/react-audio-widgets/package.json
=> chore: remove unnecessary dependencies

package-lock.json, packages/js/docs/ts/classes/Call.md, packages/js/docs/ts/classes/TelnyxRTC.md, packages/js/docs/ts/interfaces/ICallOptions.md, packages/js/docs/ts/interfaces/IClientOptions.md, packages/js/docs/ts/interfaces/INotification.md, packages/js/examples/react-audio-widgets/package-lock.json, packages/js/examples/react-audio-widgets/package.json, packages/js/examples/react-video-calling-app/package-lock.json, packages/js/examples/react-video-calling-app/package.json, packages/react-client/package-lock.json, packages/react-client/package.json
=> chore(/WEBRTC-1705): rollback react version

packages/react-client/babel.config.js, packages/react-client/jest.config.js, packages/react-client/package.json, yarn.lock
-  remove react-script from react-client 
=> chore:(WEBRTC-1718): remove react-script from react-client 

packages/js/src/Modules/Verto/messages/verto/Ping.ts, packages/js/src/Modules/Verto/messages/verto/Pong.ts, packages/js/src/Modules/Verto/tests/messages.test.ts, packages/js/src/Modules/Verto/webrtc/VertoHandler.ts, packages/js/src/Modules/Verto/webrtc/constants.ts
- add ping request to the server to keep connected
=> feat(WEBRTC-1798): add ping request to the server to keep connected

README.md
- add webrtc examples on the readme
=> chore: add webrtc examples on the readme

.github/workflows/webrtc-cdn-deploy.yml
- add new action to deploy webrtc bundle into Telnyx CDN
=> chore(ENGDESK-23386): add new action to deploy webrtc bundle into Telnyx CDN

.github/workflows/webrtc-cdn-deploy.yml
=> chore(ENGDESK-23386-gha-v1): update secrets

.github/workflows/webrtc-cdn-deploy.yml
=> chore: update secrets

.github/workflows/webrtc-cdn-deploy.yml
=> chore: revert GHA to use github runner

.github/workflows/webrtc-cdn-deploy.yml
=> chore: update

packages/react-client/.eslintrc, packages/react-client/package.json, packages/react-client/src/TelnyxRTCContext.tsx, packages/react-client/src/useCallbacks.ts, packages/react-client/src/useTelnyxRTC.ts, packages/react-client/tsconfig.json, packages/react-client/tsconfig.node.json, yarn.lock
=> chore: fix eslint

.github/workflows/draft-release.yml, .github/workflows/publish-release.yml, .github/workflows/webrtc-cdn-deploy.yml, .github/workflows/webrtc-test-release.yml
update github actions to use node v16
=> chore: update github actions to use node v16

packages/react-client/package.json
=> chore: fix types

packages/react-client/src/types/telnyx-webrtc.d.ts
=> chore: add telnyx webrtc types to react-client

packages/react-client/package.json, packages/react-client/src/types/telnyx-webrtc.d.ts, yarn.lock
Add peerDependecies t devPependencies following the rollout settings:
https://github.com/ezolenko/rollup-plugin-typescript2/issues/277
=> chore: fix deve dependencies

packages/react-client/src/telnyx-webrtc.d.ts, packages/react-client/src/typings.d.ts
=> chore: add webrtc types

packages/react-client/src/typings.d.ts
=> chore: add types

packages/react-client/CHANGELOG.md, packages/react-client/package.json
=> chore: change version

packages/js/README.md, packages/js/src/Modules/Verto/webrtc/BaseCall.ts
=> chore: update readme to include debugging instructions

packages/js/src/Modules/Verto/webrtc/BaseCall.ts
=> feat: add custom headers on bye

.github/workflows/webrtc-test-release.yml, packages/js/src/Modules/Verto/tests/messages.test.ts
=> chore: fix test

packages/react-client/src/useTelnyxRTC.ts
=> fix: add debug typespec

packages/js/src/Modules/Verto/webrtc/Peer.ts
Log `icegatheringstatechange` and `iceconnectionstatechange` events.
=> feat: log ice events

.github/workflows/draft-release.yml, .github/workflows/publish-release.yml
fixes this issue https://github.com/team-telnyx/webrtc/actions/runs/10512432646/job/29125731583
=> fix: upgrade ci to use yarn v2

.github/CODEOWNERS
=> chore: add @farhat-ha to codeowners

.github/CODEORNERS, .github/workflows/draft-release.yml, .github/workflows/publish-release.yml, .github/workflows/webrtc-cdn-deploy.yml, .github/workflows/webrtc-test-release.yml, packages/api-docs/package.json
=> chore: upgrade ci to yarn 2

.github/workflows/publish-release.yml
=> chore: update publish command

.github/workflows/publish-release.yml
=> chore: fix typo

.github/workflows/publish-release.yml
=> fix: use npm publish

.github/workflows/publish-release.yml
=> chore: remove deprecated api_docs ci

packages/js/src/Modules/Verto/webrtc/BaseCall.ts, packages/js/src/Modules/Verto/webrtc/interfaces.ts
=> chore: remove unused methods replace transfer

packages/js/src/Modules/Verto/webrtc/BaseCall.ts
=> feat: set client_state from bye message

packages/js/src/Modules/Verto/BaseSession.ts, packages/js/src/Modules/Verto/webrtc/Peer.ts
[WEBRTC-2265](https://telnyx.atlassian.net/browse/WEBRTC-2265)
[WEBRTC-2265]: https://telnyx.atlassian.net/browse/WEBRTC-2265?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: handle network disconnect connect events

packages/js/docs/ts/classes/TelnyxRTC.md, packages/js/src/Modules/Verto/BaseSession.ts, packages/js/src/Modules/Verto/BrowserSession.ts, packages/js/src/Modules/Verto/webrtc/BaseCall.ts, packages/js/src/Modules/Verto/webrtc/Call.ts, packages/js/src/Modules/Verto/webrtc/interfaces.ts, packages/js/src/TelnyxRTC.ts
[WEBRTC-2314](https://telnyx.atlassian.net/browse/WEBRTC-2314)
[WEBRTC-2314]: https://telnyx.atlassian.net/browse/WEBRTC-2314?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: add docs for customHeaders and preferred_codecs

packages/js/docs/ts/README.md, packages/js/docs/ts/classes/Call.md, packages/js/docs/ts/classes/TelnyxRTC.md, packages/js/docs/ts/interfaces/ICallOptions.md, packages/js/docs/ts/interfaces/IClientOptions.md, packages/js/docs/ts/interfaces/INotification.md, packages/js/typedoc.json
[WEBRTC-2311](https://telnyx.atlassian.net/browse/WEBRTC-2311)
[WEBRTC-2311]: https://telnyx.atlassian.net/browse/WEBRTC-2311?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: update doc generator links

packages/js/docs/ts/classes/TelnyxRTC.md, packages/js/src/TelnyxRTC.ts
=> chore: update set_codec docs

.github/workflows/update-changelog.yaml, packages/js/package.json, yarn.lock
https://telnyx.atlassian.net/browse/WEBRTC-2326
=> chore: add script to update changelog based on release body

.github/workflows/update-changelog.yaml, packages/js/CHANGELOG.md
=> fix: push new changelog

packages/js/src/Modules/Verto/util/debug.ts
[WEBRTC-2349](https://telnyx.atlassian.net/browse/WEBRTC-2349)
This change will enable collecting stats data per ICE pair candidate.
[WEBRTC-2349]: https://telnyx.atlassian.net/browse/WEBRTC-2349?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: allow stats object to be reported.

packages/js/src/Modules/Verto/util/reconnect.ts
Addresses the issue #401
Add conditional check on window object. 
=> fix: window object is not available in nextjs

packages/js/src/Modules/Verto/webrtc/Peer.ts
=> fix: add connection event is dropped

packages/js/src/Modules/Verto/webrtc/helpers.ts
[ENGDESK-38427](https://telnyx.atlassian.net/browse/ENGDESK-38427)
Attach video stream whenever you receive an invite SDP with m=video 
[ENGDESK-38427]: https://telnyx.atlassian.net/browse/ENGDESK-38427?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: attach with video when receiving m=video sdp

packages/js/CHANGELOG.md
=> chore: add missing change logs

.github/workflows/pr_review.yml
NO JIRA
Added a workflow for automatic PR reviews.
=> feat: add automatic pr_review script

packages/js/src/Modules/Verto/webrtc/BaseCall.ts, packages/js/src/Modules/Verto/webrtc/helpers.ts, packages/js/src/Modules/Verto/webrtc/interfaces.ts
NO_JIRA
Disable automatic video response in favor of having the option to toggle on and off via answer params.
=> fix: disable automatic video response in favor of answer option

packages/js/docs/ts/README.md, packages/js/docs/ts/classes/PreCallDiagnosis.md, packages/js/docs/ts/interfaces/MinMaxAverage.md, packages/js/docs/ts/interfaces/PreCallDiagnosisOptions.md, packages/js/docs/ts/interfaces/RTCIceCandidateStats.md, packages/js/docs/ts/interfaces/Report.md, packages/js/docs/ts/interfaces/TelnyxIDs.md, packages/js/src/Modules/Verto/util/constants/index.ts, packages/js/src/Modules/Verto/webrtc/Peer.ts, packages/js/src/PreCallDiagnosis.ts, packages/js/src/index.ts, tsconfig.json
[WEBRTC-2463](https://telnyx.atlassian.net/browse/WEBRTC-2463)
Implement a new feature: Pre-call diagnosis, 
The gist is we make a call to a texML number to measure metrics about network quality and detect any potential problems with the client's setup. 
[WEBRTC-2463]: https://telnyx.atlassian.net/browse/WEBRTC-2463?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: implement pre-call diagnosis

packages/js/src/Modules/Verto/webrtc/Peer.ts, packages/js/src/PreCallDiagnosis.ts, packages/js/src/index.ts, packages/js/src/utils/mos.ts
[WEBRTC-2498](https://telnyx.atlassian.net/browse/WEBRTC-2498)
1. Refactor MOS calculation and quality interpretation
2. Create a new event emitted every second that contains data about the peer connection (quality, mos, jitter, rtt) 
[WEBRTC-2498]: https://telnyx.atlassian.net/browse/WEBRTC-2498?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: implement real time call quality metrics

packages/js/README.md, packages/js/src/Modules/Verto/webrtc/BaseCall.ts, packages/js/src/Modules/Verto/webrtc/helpers.ts, packages/js/src/Modules/Verto/webrtc/interfaces.ts
=> chore: update docs for pre-call diagnosis and realtime quality metrics features. 

packages/js/CHANGELOG.md
=> chore: update CHANGELOG.md

packages/js/README.md, packages/js/src/utils/interfaces.ts
Update anonymous_login / AI assistant login and call documentation
followup to #421
=> chore(doc): update readme for anonymous login

packages/js/src/Modules/Verto/util/debug.ts, packages/js/src/Modules/Verto/webrtc/BaseCall.ts, packages/js/src/Modules/Verto/webrtc/Peer.ts
[ENGDESK-39946](https://telnyx.atlassian.net/browse/ENGDESK-39946)
1. Refactored the debug stats logic all in the same place. 
2. Fixed the issue with the debug output not being generated correctly.
[ENGDESK-39946]: https://telnyx.atlassian.net/browse/ENGDESK-39946?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: debug report file is not generated

packages/js/src/Modules/Verto/services/Connection.ts, packages/js/src/Modules/Verto/util/constants/index.ts, packages/js/src/Modules/Verto/webrtc/BaseCall.ts, packages/js/src/Modules/Verto/webrtc/Peer.ts, packages/js/src/Modules/Verto/webrtc/VertoHandler.ts
NO_JIRA
- Reduce the number of ICE servers
- Remove unnecessary SDP munging in remote description (Its already handled on the backend side)
- Suppress warnings for unknown verto methods to support new messages.
=> fix: improve p2p connection establishment time

.github/workflows/update-changelog.yaml
Add a workaround for update CHANGELOG.md CI 
=> fix: add fetch-depth

packages/js/src/Modules/Verto/services/Connection.ts, packages/js/src/Modules/Verto/util/interfaces.ts, packages/js/src/utils/interfaces.ts
NO JIRA
Add options to select b2bua-rtc ip and port
=> feat: add rtcIp and rtcPort options
