team-telnyx/webrtc

- examples/react/stories/2-WebDialer.stories.js
- src/VertoClient/VertoClient.ts
[ENGDESK-3732](https://telnyx.atlassian.net/browse/ENGDESK-3732)
add support to pass hostname and port by url parameters
1. cd examples/react
2. access this url http://localhost:6006/?path=/story/webdialer--example
3. put whatever you want in query string url
For example:
http://localhost:6006/?path=/story/webdialer--example&host=rtc.telnyx.com&port=1500  
4. See if show more two options in layout host and port
| Desktop     | ![image](https://user-images.githubusercontent.com/16343871/72352280-bcf4c500-36c0-11ea-9869-4b77421f47a1.png)|
| Desktop 2 | ![image](https://user-images.githubusercontent.com/16343871/72352176-87e87280-36c0-11ea-966f-e871ae454843.png)|
> feat(ENGDESK-3732): add support to pass host and port by url parameters

- .github/PULL_REQUEST_TEMPLATE.md
- examples/react/stories/2-WebDialer.stories.js
- src/TelnyxRTC/RTC.ts
Changed method addStream deprecated to addTrack.
Changed method createOffer deprecated to createOffer new interface.
Changed method createAnswer deprecated to createAnswer new interface.
Added answer button to answer a received call.
1. cd examples/react
2. run yarn setup
3. run yarn storybook
4. make a call and receive a call
> fix(WEBRTC-54):  add support to make and receive call in Safari  

- src/Modules/Verto/BrowserSession.ts
- src/Modules/Verto/tests/Verto.test.ts
- src/Modules/Verto/tests/webrtc/Call.test.ts
- src/Modules/Verto/webrtc/BaseCall.ts
- src/Modules/Verto/webrtc/helpers.ts
Added helper function to handle inside Telnyx the call state. this function `setStateTelnyx` will be used at Telnyx inside projects, this way is easier to handle call's.
For example instead of using all these states 
```
switch (notification.type) {
case 'callUpdate':
// Call is over and can be removed
if (
notification.call.state === 'hangup' ||
notification.call.state === 'destroy'
) {
activeCall = null;
}
// An established and active call
if (notification.call.state === 'active') {
return;
}
// New calls that haven't started connecting yet
if (notification.call.state === 'new') {
return;
}
// Receiving an inbound call
if (notification.call.state === 'ringing') {
return;
}
// Call is active but on hold
if (notification.call.state === 'held') {
return;
}
break;
}
```
At Telnyx we only …
> feat(WEBRTC-108): Added helper function to handle inside Telnyx the call state

- examples/react/stories/1-ClickToCall.stories.js
- examples/react/stories/2-WebDialer.stories.js
- examples/vanilla/index.html
- src/Modules/Verto/BaseSession.ts
- src/Modules/Verto/index.ts
- src/Modules/Verto/messages/verto/Login.ts
- src/Modules/Verto/tests/helpers.test.ts
- src/Modules/Verto/tests/messages.test.ts
- src/Modules/Verto/util/helpers.ts
- src/Modules/Verto/util/interfaces.ts
- Was added a new prop `login_token` to handle the register on FreeSWITCH using an ephemeral JWT token.
- Updated the ClickToCall.stories.js example.
1. yarn build
2. cd examples/react && npm i && npm run setup && npm run storybook
3. get your credentials on the customer portal
4. make a call.
> feat(ENGDESK-5656): added support to login with ephemeral token

- .eslintignore
- .eslintrc.json
- .gitignore
- package-lock.json
- package.json
- src/BaseClient.ts
- src/Modules/Verto/BrowserSession.ts
- src/Modules/Verto/index.ts
- src/Modules/Verto/util/constants/index.ts
- tsconfig.json
- Added and configured ESlint and Husky
1. run `npm run build`
2. check if the build was generated successfully
> feat(WEBRTC-121): Added and configured ESlint and Husky

- package-lock.json
- package.json
- src/Modules/Verto/index.ts
- src/Modules/Verto/webrtc/Peer.ts
- Fixed audio call problem on Firefox due to the **createOffer** method being called with both options of MediaStream enabled
`{ offerToReceiveAudio: true, offerToReceiveVideo: true }` even though I only use an **audio** options.
In the future, when we support `unified-plan` we will need to change this 
```
{ offerToReceiveAudio: true, offerToReceiveVideo: true }
```
To: 
```
addTransceiver('audio')
```
These options are legacy
https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/createOffer
1. In root folder `npm i ` && `npm run build`
2. Navigate into `examples/react`
3. Run `npm i` && `npm run setup` && `npm run start`
4. Open the example in a Firefox browser and try to make a call and answer
> fix(WEBRTC-124): fixed audio call on Firefox browser

- examples/react/stories/components/WebDialer.jsx
- src/Modules/Verto/index.ts
- Removed unnecessary code that ran without user and password. 
1. `npm i` && `npm run build`
2. Navigate into `examples/react`
3. Provide your user and password wrongly and try to make a call
4. See in the console log the message error `Authentication Failed`
5. Refresh the page and provide your user and password rightly and try to make a call
6. Check in the console log that you don't have the error about `Authentication required`
> fix(WEBRTC-134) - Authentication required

- src/Modules/Verto/webrtc/BaseCall.ts
- added new fields to show friendly messages of errors
1. 'npm i' && 'npm run build'
2. navigate into `examples/react`
3. 'npm i' && 'npm setup' && 'npm start'
4. Make a call to an invalid number and see on logs with have theses fields
```
sipCallId: "70555126-56dd-4647-be2e-2a5e0f87677b"
sipCode: 404
sipReason: "Invalid number: 23423423423423423423"
```
| Desktop     |![image](https://user-images.githubusercontent.com/16343871/89942251-9bc26b80-dbf2-11ea-9381-a11c2c930bca.png)|
> feat(WEBRTC-141): added new fields to show friendly messages of errors

- packages/js/README.md
Link to JWT quickstart guide and remove non-working `call.transfer` example.
> README improvements, JWT examples

- packages/js/README.md
`call.reject()` is not available in the newest version of the SDK, but the
example was never updated.
> Fix README documentation on rejecting a call

- packages/js/src/Modules/Verto/webrtc/BaseCall.ts
- Add **cause** and **causeCode** when hangup the call
This change was necessary to avoid the necessity of click in hang-up many times.
1. navigate into `packages/js` and run `yarn build`
2. navigate into `packages/js/examples/react-audio` and `npm i` && `npm run setup`
3. Use the WebDialer to make a call to react-audio and when the incoming call arrives click in hang up button.
4. See if on the react-audio app the call doesn't come again automatically.
> fix(ENGDESK-6713): add cause and causeCode when hangup the call

- packages/js/src/Modules/Verto/webrtc/Peer.ts
- packages/js/src/Modules/Verto/webrtc/interfaces.ts
Extends interface of `RTCConfiguration` to use during the [Unified Plan SDP format transition](https://webrtc.org/getting-started/unified-plan-transition-guide) instead of ignoring the TypeScript error.
> Add transitionary Chrome RTCConfiguration interface

- packages/js/README.md
- packages/react-native/README.md
Updates GitHub paths in READMEs to point to `main`.
To switch your local remote to main:
```shell
$ git checkout master
$ git branch -m master main
$ git fetch
$ git branch --unset-upstream
$ git branch -u origin/main
```
> Change default branch to `main`

- packages/js/src/Modules/Verto/tests/Verto.test.ts
- packages/js/src/Modules/Verto/util/constants/index.ts
Error:
- When it tries to make a video call using vanilla example, the code was returning `Codec ERROR`
Solution:
- We checked the port from STUN/TURN server and figure out that the port was wrong for the STUN server, so we change the STUN_SERVER port from 3843 to 3478.
1. Access the `package/js/example/vanilla`
2. fill your credentials and try to make a video call using Chrome Browser
3. You should see your local video and the remote video.
> fix(ENGDESK-7173): change the STUN_SERVER port from 3843 to 3478

- packages/js/examples/react-audio/stories/2-WebDialer.stories.js
- packages/js/examples/react-audio/stories/components/WebDialer.jsx
- packages/js/src/Modules/Verto/BrowserSession.ts
Documents usage of microphone enable/disable methods
1. Run Storybook in `examples/react-audio`
2. Go to the WebDialer example (http://localhost:6006/?path=/story/webdialer--example)
3. Enter in your information and make a call to a second client. Verify that you hear audio on the second client
4. Check "Disable Microphone" in Storybook Knobs and make another call. Verify that you do not hear audio
5. Uncheck "Disable Microphone" and make another call. Verify that you hear audio again
> Test microphone methods

- packages/js/examples/react-audio/stories/Utilities.stories.js
- packages/js/examples/react-audio/stories/components/Utilities.jsx
- packages/js/src/Modules/Verto/BrowserSession.ts
- packages/js/src/Modules/Verto/webrtc/helpers.ts
Documents getting audio input and output devices.
1. Run `npm run build` in `packages/js`
2. Run `npm start` in `packages/js/examples/react-audio`
3. Navigate to http://localhost:6006/?path=/story/utilities--example
4. Click "Get Audio Input Devices". Verify your input devices are displayed
5. Click "Get Audio Output Devices". Verify your input devices are displayed (see note about browser compatibility below)
Firefox doesn't return an audio output device list. I've documented this in the comments.
Firefox:
Chrome:
> Document getting audio devices

- packages/js/src/Modules/Verto/BrowserSession.ts
Add type doc for disable and enable webcam methods
1. cd `package/js/example/vanilla`
2. open the index.html file
3. disable checkbox video and make a call
4. you should **not see** the local videos.
1. enable checkbox video and make a call
2. you should **see** the videos.
1. access `newCall` and set `video: false`
2. enable checkbox video and make a call
3. you should **not see** the local video.
> add type doc for disable and enable webcam methods

- packages/js/src/TelnyxRTC.ts
Overwrote the constructor in the TelnyxRTC class because the docs talk
about the creation of the TelnyxRTC class, instead of any of the
inhereted classes. It would be wrong to document BrowserSessions
constructor as creating a TelnyxRTC instance.
> docs: Add TelnyxRTC constructor docs

- packages/js/examples/react-audio/stories/components/Utilities.js
- packages/js/src/Modules/Verto/BrowserSession.ts
- Add typedoc on getDevices method
- Create a utility method to test
1. Navigate into `package/js/examples/react-audio`
2. Run `npm i && npm start`
3. Access http://localhost:6006/?path=/story/utilities--example
4. Clinck on the button Get Device List
| Desktop     |![image](https://user-images.githubusercontent.com/16343871/100238169-a63d1280-2f0e-11eb-9d9b-bb9ea0301a72.png)|
> feat(WEBRTC-227): add typedoc on getDevices method and create  a utility method to test

- packages/js/examples/react-audio/stories/components/Utilities.js
- packages/js/src/Modules/Verto/BrowserSession.ts
- Add typedoc on getDeviceResolutions method
- Create a utility method to test
1. Navigate into `package/js/examples/react-audio`
2. Run `npm i && npm start`
3. Access http://localhost:6006/?path=/story/utilities--example
4. Clinck on the button Get Device Resolutions
| Desktop     |![image](https://user-images.githubusercontent.com/16343871/100284667-48c8b600-2f4e-11eb-9ff4-6d3d1520ec69.png)|
> feat(WEBRTC-226): add typedoc on getDeviceResolutions method and create a utility method to test

- packages/js/src/Modules/Verto/BaseSession.ts
- packages/js/src/Modules/Verto/index.ts
- packages/js/src/Modules/Verto/webrtc/constants.ts
We don't support `refreshToken` methods, so I removed these methods related to JWT expiration.
1. Navigate into `package/js` && npm run build && `npm run test`
2. Run `npm pack` get the `.tgz` file and install inside `examples/react-video` using `npm i`
3. Make a call and receive a call to see if it is working.
> feat(WEBRTC-232): remove refreshToken and blade methods

- packages/js/examples/react-audio/stories/components/Utilities.js
- packages/js/src/Modules/Verto/BaseSession.ts
Documents `connected` property on client
1. Run storybook app in `js/examples/react-audio`
2. Go to http://localhost:6006/?path=/story/utilities--example
3. Click `connect`. Verify "Connected" message displays
> Document connected property

- .github/workflows/webrtc-draft-release.yml
- packages/js/package.json
Adds step to draft release workflow that generates and commits `js/docs` changes.
> Update docs when drafting release

- packages/js/examples/react-audio/stories/components/Utilities.js
- packages/js/src/Modules/Verto/BrowserSession.ts
- add typedoc on setAudioSettings method
1. Navigate into `package/js/examples/react-audio`
2. Click on `Set Audio Settings` button
3. See if returns an object with the default mic label and with the applied settings.
| Desktop     |![image](https://user-images.githubusercontent.com/16343871/100622695-eb42b980-32ff-11eb-990f-5a89aa5c194b.png)|
> docs(WEBRTC-233): add typedoc on setAudioSettings method

- packages/js/examples/react-audio/stories/components/Utilities.js
- packages/js/src/Modules/Verto/BrowserSession.ts
- add typedoc on setVideoSettings method
1. Navigate into `package/js/examples/react-audio`
2. Click on `Set Video Settings` button
3. See if returns an object with the default mic label and with the applied settings.
| Desktop     |![image](https://user-images.githubusercontent.com/16343871/100632914-2b0f9e00-330c-11eb-8d4e-6505d5c9e456.png)|
> docs(WEBRTC-234): add typedoc on setVideoSettings method

- .github/workflows/publish-release.yml
- .github/workflows/webrtc-draft-release.yml
- .github/workflows/webrtc-test-release.yml
- packages/js/package.json
Prevents creating a git tag and bumping package.json on merge to `main`, so that we can merge multiple times without generating multiple versions.
> Fix changelog versioning

- packages/js/examples/react-audio/stories/components/Utilities.js
- packages/js/src/Modules/Verto/BrowserSession.ts
Documents speaker getter & setter, adds manual testing utility
1. Run storybook app in `js/examples/react-audio`
2. Go to http://localhost:6006/?path=/story/utilities--example in Chrome
3. Choose a different speaker and click "Update"
4. Click "Get Speaker". Verify that the new speaker is returned
> Document speaker property

- packages/js/src/Modules/Verto/BaseSession.ts
Documents possible event names in `on` method.
Note: I did some research into ways to document event names in a similar fashion but didn't find a solution that rendered nicely with typedoc. I've tried documenting the enum directly, but wasn't getting a typedoc output at all. Open to other ideas.
Ran `npm run docs` and previewed the output:
> Document event types

- packages/js/src/Modules/Verto/webrtc/BaseCall.ts
Adds TSDoc comment to `.dtmf`
1. Start Storybook: `cd packages/js/examples/react-audio && npm start`
2. Go to http://localhost:6006/?path=/story/webdialer--example and fill in your username, password etc.
3. Dial the Telnyx Chicago number: `+13129457420`
4. Click `9` to access the directory. Verify that you hear the directory listing
> Document DTMF method

- packages/js/examples/react-audio/stories/components/WebDialer.jsx
- packages/js/src/Modules/Verto/webrtc/BaseCall.ts
Documents hold, unhold and toggle hold.
1. Start Storybook: `cd packages/js/examples/react-audio && npm start`
2. Go to http://localhost:6006/?path=/story/webdialer--example and fill in your username, password etc.
3. Make a call to another device that you can access
4. Place call on hold by clicking on "play"/triangle symbol button. Verify that line held becomes silent
5. Unhold the call by clicking button again. Verify that line is unheld
> Document hold/unhold

- packages/js/README.md
- packages/react-native/README.md
Change the URL path from screenshot to show correctly on npm registry
https://www.npmjs.com/package/@telnyx/webrtc
> chore: fix screenshot url to show on the npm registry

- packages/js/examples/react-audio/stories/components/WebDialer.jsx
- packages/js/src/Modules/Verto/webrtc/BaseCall.ts
Documents `muteAudio`, `unmuteAudio` and `toggleAudioMute`
1. Start Storybook: `cd packages/js/examples/react-audio && npm start`
2. Go to http://localhost:6006/?path=/story/webdialer--example and fill in your username, password etc.
3. Make a call to another device that you can access
4. Mute the call. Verify that you can't hear yourself on the other line
5. Unmute the call. Verify that you can hear yourself again
> Document mute/unmute/toggle audio

- packages/js/src/Modules/Verto/webrtc/BaseCall.ts
Document `setAudioInDevice`
1. Log in to https://webrtc.telnyx.com/rtc/index.html
2. Make a call to another destination you own. Verify you can hear audio on the other line
3. Switch microphone (https://github.com/team-telnyx/rtc-demo-2/blob/fa191a57545ed3a948f51fa2668f34609b1b4694/rtc/src/App.js#L381). Verify you can still hear audio, from a different microphone
> Document setting audio input device

- packages/js/examples/react-video/src/components/phone/Dialog.js
- packages/js/src/Modules/Verto/webrtc/BaseCall.ts
Documents `muteVideo`, `unmuteVideo` and `toggleVideoMute`.
IMO it'd be clearer to rename this something like `turnOffVideo`, `turnOnVideo` and `toggleVideo` since this method effects video visibility as well as audio, thoughts?
1. Start `react-video` Storybook app and login
2. Make a video call. Verify that you see the video stream
3. Mute the video. Verify that the video is now hidden and silent for the other participant
Known issue on Firefox
> Document mute/unmute/toggle video

- packages/js/src/Modules/Verto/index.ts
- packages/react-client/example/src/Phone.tsx
Removes references to async/Promises in `newCall` doc.
Addresses [issue reported in Slack](https://telnyx.slack.com/archives/CM7AYEY78/p1607695278120900?thread_ts=1607643941.120500&cid=CM7AYEY78)
1. Re-link and run `react-client/example`
2. Make a new call with a destination number. Verify app does not crash
> Fix new call documentation

- packages/js/src/Modules/Verto/webrtc/Call.ts
- add typedoc on method setAudioOutDevice
1. Access webdialer and make a call
2. When a call is active you can select another Speaker 
3. You can see the implementation here https://github.com/team-telnyx/rtc-demo-2/blob/master/rtc/src/App.js#L405
> docs(WEBRTC-252): add typedoc on method setAudioOutDevice

- packages/js/src/Modules/Verto/webrtc/BaseCall.ts
- add typedocs on internal call properties.
1. See the comments on PR files
> docs: add typedocs on internal call properties

- packages/js/src/Modules/Verto/BrowserSession.ts
- packages/js/src/Modules/Verto/webrtc/BaseCall.ts
- add typedoc on methods getVideoDevices and setVideoDevice
1. Access [web dialer](https://webrtc.telnyx.com/rtc/index.html)
2. Make a call with video options enabled.
3. You should see a select box with your webcam devices.
4. Pick a webcam and see if the video change to the right webcam.
> docs(WEBRTC-253): add typedoc on methods getVideoDevices and setVideoDevice

- packages/js/src/Modules/Verto/BrowserSession.ts
- packages/js/src/Modules/Verto/webrtc/BaseCall.ts
-  add typedoc on local and remote stream properties
1. Internal documentation
> docs(WEBRTC-266-267): add typedoc on local and remote stream properties

- README.md
- packages/js/README.md
- packages/js/src/TelnyxRTC.ts
Streamlines the @telnyx/webrtc README by cross-linking with examples in docs, to reduce the amount of duplicated (and erroneous) example code.
Side by side comparison: [Current README](https://github.com/team-telnyx/webrtc/blob/main/packages/js/README.md) | [Proposed README](https://github.com/team-telnyx/webrtc/blob/Update_js_readme/packages/js/README.md)
> Streamline JS README

- packages/api-docs/package.json
- packages/js/README.md
- packages/js/src/Modules/Verto/webrtc/BaseCall.ts
- packages/js/src/Modules/Verto/webrtc/Call.ts
- packages/js/src/utils/interfaces.ts
Removes support for `@link` tag in Typedoc comments for simpler developer docs MVP.
> Remove support for link tag

- packages/js/src/Modules/Verto/BaseSession.ts
- packages/js/src/Modules/Verto/webrtc/Call.ts
- packages/js/src/TelnyxRTC.ts
Add overview content to `Client` and `Call` for display on developer docs.
> Add dev docs category overviews

- packages/react-client/README.md
- packages/react-client/example/package.json
- packages/react-client/example/src/Phone.tsx
- packages/react-client/example/src/VideoCall.tsx
- packages/react-client/package-lock.json
- packages/react-client/package.json
- packages/react-client/src/useTelnyxRTC.ts
- Move `@telnyx/webrtc` from peer dependency to dependencies for easier version management
- Update options to reflect new webrtc exported interface following https://github.com/team-telnyx/webrtc/pull/132
This will need to be released with a major version bump to prevent versioning issues for end users.
- Developer docs JS SDK instructions will need to be updated
1. `packages/react-client`: Run `npm install` and `npm run build`
2. `packages/react-client/example`: Run `npm install --no-package-lock`
3. `packages/react-client/example`: Run `npm start` and make a call. Verify app functions as expected
> Update webrtc package imports

- packages/react-client/example/src/App.tsx
- packages/react-client/src/useTelnyxRTC.ts
Reconnect React client on credential changes, for example if a token is set after initiating the provider.
1. [`packages/react-client`]: `npm install && npm run build`
2. [`packages/react-client/example`]: `npm install --no-package-lock`
3. [`packages/react-client/example`]: `npm start`
4. Enter in a login token and click "update token". Verify calling works
5. Generate and enter a new login token and click "update token". Verify calling still works
> Reconnect React client on credential update

- packages/js/src/Modules/Verto/webrtc/BaseCall.ts
- packages/js/src/Modules/Verto/webrtc/VertoHandler.ts
- packages/js/src/Modules/Verto/webrtc/helpers.ts
- packages/js/src/Modules/Verto/webrtc/interfaces.ts
- add delay when call stop playing audio, because it should call pause method after play method
1. Access any WebRTC project and add the "auto-answer" method
```
if (notification.call.state === 'ringing') {
notification.call.answer();
}
```
2. open two instances of WebRTC app and make a call to each other
3. You shouldn't get any errors on the console and you should hear the audio playing and stop the audio.
> fix(WEBRTC-362): add delay when call stop play audio, because it should call pause method after play method

- packages/js/examples/react-audio-widgets/stories/Utilities.stories.js
- packages/js/examples/react-audio-widgets/stories/components/Utilities.js
- fix utilities examples from storybook
1. Navigate into `packages/js/exmples/react-audio-widgets`
2. Run `npm i` && `npm run storybook`
3. Access http://localhost:6006/?path=/story/utilities--example 
4. Click in some buttons to see the results.
| Desktop     |![image](https://user-images.githubusercontent.com/16343871/109052157-126c1580-76ba-11eb-8899-37732ace9ef2.png)|
> fix(WEBRTC-384): fix utilities examples from storybook

- packages/js/README.md
- packages/js/src/TelnyxRTC.ts
- add documentation to call off event method when call client.disconnect.
1. Open README from `packages/js` and see the new doc
> docs(WEBRTC-355): add documentation to call off event method when call client.disconnect.

- packages/js/src/Modules/Verto/tests/webrtc/VertoHandler.test.ts
- packages/js/src/Modules/Verto/webrtc/VertoHandler.ts
- packages/js/src/Modules/Verto/webrtc/interfaces.ts
- packages/js/src/utils/interfaces.ts
- add client state on build call to be able to use on call control
1. Navigate into `packages/js` and run `npm run build`
2. Open any example from `packages/js/examples/*`
3. on the method `newCall` pass the `clientState` as argument.
4. Open the network tab from browser, access the tab `WS`
5. Make a call.
6. See on `WS` messages, on the `invite` message if ou can see the `clientState` param. 
| Desktop     |![image](https://user-images.githubusercontent.com/16343871/108745422-ce420f00-7519-11eb-91a4-03f503b9d07e.png)|
> feat(WEBRTC-376): add client state on build call to be able to use on call control

- packages/js/examples/react-audio-widgets/package-lock.json
- packages/js/examples/react-audio-widgets/package.json
- packages/js/examples/react-video-calling-app/package-lock.json
- packages/js/package-lock.json
- packages/js/package.json
Update dependency vulnerabilities
1. Navigate into `packages/js`
2. Run  `npm i` and `npm run build` and `npm run test` 
3. After that run `npm audit`
4. You should get 0 vulnerabilities.
> chore(ENGDESK-8552): update dependency vulnerabilities

- packages/js/src/Modules/Verto/webrtc/BaseCall.ts
- packages/js/src/Modules/Verto/webrtc/interfaces.ts
[WEBRTC-577](https://telnyx.atlassian.net/browse/WEBRTC-577)
Enable dynamic bandwidth selection
1.1 Start a call
1.2 Open "Media settings' subpage in rtc-demo-2 app
1.2 Set bandwidth and click apply
1.3 See changes taking effect by inspection of webrtc-internals
> Add dynamic bandwidth selection

- packages/js/src/Modules/Verto/services/Connection.ts
- packages/js/src/Modules/Verto/tests/webrtc/Call.test.ts
- packages/js/src/Modules/Verto/webrtc/BaseCall.ts
- packages/js/src/Modules/Verto/webrtc/Peer.ts
- packages/js/src/Modules/Verto/webrtc/VertoHandler.ts
- packages/js/src/Modules/Verto/webrtc/constants.ts
- packages/js/src/Modules/Verto/webrtc/helpers.ts
- packages/js/src/Modules/Verto/webrtc/interfaces.ts
- packages/js/src/utils/interfaces.ts
This makes possible to control codecs outgoing bitrate on a running call,
and displays bitrate on a chart. 
1. Make a call
2. Switch to a new tab on Panel settings, named 'Media settings'
3. Input bitrate and click Apply
4. Observe changes taking effect on chart
5. Confirm values make sense with webrtc-internals, etc
TODO
> [WEBRTC-577 WEBRTC-578 WEBRTC-613 WEBRTC-614] Dynamic bandwidth control

- packages/js/package.json
A minor change adding a watch option using rollup, this is handy for development
> chore: add watch option for pkg development

- packages/js/src/Modules/Verto/webrtc/BaseCall.ts
- packages/js/src/Modules/Verto/webrtc/interfaces.ts
https://telnyx.atlassian.net/browse/WEBRTC-637
This adds getStats call to pulbic interface of IWebRTCCall.
The purpose is to enable user to register callback for async stats.
User can call getStats with callback (stats processor) and optional filter on the stats reports.
On each RTCStatsReport the caller's callback gets called with report if report passes user's filter,
or if there is no filter at all.
Filter passing is implemented with the following logic:
- if there is no filter supplied, call user's callback with report
- if there is filter, then for each property present on filter object:
- if the report's property value doesn't match filter's property value, or if there is no this property on report, then do not call user's callback, otherwise all props match - call user's callback …
> WEBRTC-635 Enable async stats

- packages/js/docs/ts/interfaces/icalloptions.md
- packages/js/package-lock.json
- packages/js/package.json
- packages/js/rollup.config.js
- packages/js/src/Modules/Verto/webrtc/BaseCall.ts
- packages/js/src/utils/interfaces.ts
- packages/js/tsconfig.json
- Add user agent for call volume track
1. Navigate to 'package/js' and run `npm run build`
2. Choose one of the examples in `examples` folder and make a `link`
3. Make a call and see if you can find the `User-Agent` in `WS` messages in browser.
| Desktop     | ![image](https://user-images.githubusercontent.com/16343871/129761952-b0a7fe5d-cbe6-48c9-8823-1c94eff20000.png)|
> feat(WEBRTC-642): Add user agent for call volume track

- packages/js/src/Modules/Verto/BrowserSession.ts
- packages/js/src/Modules/Verto/webrtc/helpers.ts
-  asking for permission on the browser when calling methods that require audio output devices
1. Navigate to `js/examples/react-audio-widget`
2. Run `npm run setup` and `npm run storybook`
3. Access http://localhost:6006/?path=/story/utilities--examples in an incognito tab
4. Click on `Get output audio devices` button and see if will prompt a modal asking for permission.
5. Click in Allow and see if it returns the audio output device list 
| Desktop     |![image](https://user-images.githubusercontent.com/16343871/132051488-acabc827-246c-41bb-ab26-66a03986c033.png)|
> fix(ENGDESK-11008): asking for permission on the browser when calling methods that require audio output devices

- packages/js/.eslintrc.json
- packages/js/examples/react-audio-widgets/stories/components/ClickToCall.jsx
- packages/js/examples/react-audio-widgets/stories/components/WebDialer.jsx
- packages/js/examples/react-video-calling-app/src/App.js
- packages/js/examples/vanilla-js-app/index.html
- packages/js/src/Modules/Verto/messages/verto/Gateway.ts
- packages/js/src/Modules/Verto/tests/webrtc/VertoHandler.test.ts
- packages/js/src/Modules/Verto/webrtc/VertoHandler.ts
- packages/js/src/Modules/Verto/webrtc/constants.ts
- add gateway state messages to have the certainty that the user is registered before make a new call
1. Navigate into `js` folder and run `npm run build`
2. Pointing in the `index.html` the script `lib/bundle.js` file.
3. Go to `examples/vanilla/index.html` and try to register the user and see if the server sends the messages to `REGED` before sends the `invite` message
| Desktop     |![image](https://user-images.githubusercontent.com/16343871/132724861-032be4a9-c10a-4317-989b-c47962283d67.png)|
> feta(WEBRTC-683): add gateway state messages to have the certain that the user is registered before make a new call

- packages/js/src/Modules/Verto/BaseSession.ts
- packages/js/src/Modules/Verto/index.ts
- packages/js/src/Modules/Verto/util/interfaces.ts
- packages/js/src/Modules/Verto/webrtc/VertoHandler.ts
- enabling auto-reconnect on gateway FAIL
This new version will add an auto-reconnect feature when SDK receives FAIL and FAIL_WAIT from the server.
To keep your own reconnect implementation in your UI client inside the` telnyx.error` notification, please add `autoReconnect: false` in your TelnyxRTC instance. 
For example:
```
new TelnyxRTC({
login_token: "********",
autoReconnect: false
});
```
With `autoReconnect: false` the SDK won't try to reconnect automatically so you will need to do this in your application.
If you want that the Telnyx SDK do the auto-reconnect for you. You don't need to set `autoReconnect`, because it is `true` by default.
So when the server sends FAIL or FAIL_WAIT the SDK will try to reconnect automatically three times in the background keeping your connection …
> fix(WEBRTC-707): enabling auto reconnect on gateway FAIL

- packages/js/.eslintrc.json
- packages/js/src/Modules/Verto/index.ts
- packages/js/src/Modules/Verto/messages/verto/Gateway.ts
- packages/js/src/Modules/Verto/services/Connection.ts
- packages/js/src/Modules/Verto/services/Handler.ts
- packages/js/src/Modules/Verto/tests/webrtc/VertoHandler.test.ts
- packages/js/src/Modules/Verto/webrtc/ErrorResponse.ts
- packages/js/src/Modules/Verto/webrtc/VertoHandler.ts
- packages/js/src/Modules/Verto/webrtc/constants.ts
- packages/js/src/TelnyxRTC.ts
- REGED message with `result` prop was not firing `telnyx.ready` event
1. try to reconnect many times using the JWT_Token and see if it is firing the `telnyx.ready` event
> fix(WEBRTC-723): REGED message with result prop was not firing telnyx.ready event

- packages/js/src/Modules/Verto/tests/setup/browsers.ts
- packages/js/src/Modules/Verto/tests/webrtc/helpers.test.ts
- packages/js/src/Modules/Verto/webrtc/helpers.ts
the recursive call to getDevices when the browser does not support audio output like Safari and Firefox.
The issue was happening when the browser does not support audio output and
it returns a device list with an empty array when the code received an empty device list it was trying to call getUserMedia and getDevices to fulfilled with data,
but as the browser does not support audio output it was executing the getDevices method in an infinite loop.
To solve it I removed the recursion of getDevice method and now I'm checking first if the user gave permission to list devices, if yes I return a list of devices with all the data fulfilled else I trigger an error and I return an empty array without any device.
| ----------- | …
> fix(WEBRTC-746): recursive call to getDevices when the browser does not support audiooutput like Safari and Firefox.

- packages/js/package.json
- packages/js/src/Modules/Verto/BaseSession.ts
- packages/js/src/Modules/Verto/services/Connection.ts
- packages/js/src/Modules/Verto/util/helpers.ts
- packages/js/src/Modules/Verto/util/interfaces.ts
- packages/js/src/Modules/Verto/util/tests/helpers.test.ts
- packages/js/src/Modules/Verto/webrtc/VertoHandler.ts
- add code to avoid multiples REGED messages on the client-side
1. You can run any example project inside `packages/js/examples`
2. Make a npm link
3. Register in the SDK and see if the `telnyx.ready` will dispatch only once.
| Desktop     |![image (12)](https://user-images.githubusercontent.com/16343871/145574104-d98b6965-4bae-49e2-b628-ae23b55eae2e.png)|
> fix(ENGDESK-12851): add code to avoid multiples REGED messages on the client side

- packages/js/src/Modules/Verto/services/Connection.ts
- change previousGatewayState only if gateway state exist to avoid send many REGISTER messages
> fix: change previousGatewayState only if gateWayState exist to avoid send many REGISTER messages

- packages/js/src/Modules/Verto/BaseSession.ts
- packages/js/src/Modules/Verto/webrtc/VertoHandler.ts
- Change the timeout value of 500 to use a random number between 3000 and 5000 milliseconds to avoid many users trying to connect to the server at the same time.
1. Navigate into `packages/js` and run  `npm run build `
2. Open another project with a web dialer and run `npm link`
3. Try to make many registrations and see if the time change
| Desktop     |![image](https://user-images.githubusercontent.com/16343871/148072684-daf375e8-8fd0-4ca8-b6c4-545dbb2ed161.png)|
> fix(WEBRTC-757): change the timeout value of 500 to use a random number

- package.json
- yarn.lock
- add yarn resolutions to override "buggy" dependency version with the fixed dependency version
The intention here is to fix these alerts
> chore(WEBRTC-1719): add resolution in package json

- package.json
- yarn.lock
- upgrade libs to fix vulnerability issues
1. Run `yarn`
2. Navigate to `package/js` and run `yarn build` and `yarn link`
1. Access http://localhost:3000 from the Web dialer and link the SDK
3. Register and make a call
4. It should work as usual.
| Desktop     |![image](https://user-images.githubusercontent.com/16343871/177624112-9afe9851-4a61-4195-8810-61277632913e.png)|
> chore(WEBRTC-2021): upgrade libs to fix vulnerability issues

- packages/js/package.json
- packages/js/src/Modules/Verto/BrowserSession.ts
- packages/js/src/Modules/Verto/webrtc/interfaces.ts
- packages/js/src/utils/interfaces.ts
- An external customer was complaining about the Voice SDK installation. The SDK was returning an error message saying that it was not possible to find the types for `@telnyx/webrtc`.
Error: 
Fix:
We were pointing to the wrong path to load the types.
0. navigate to `package/js`
1. run `yarn build --watch`
2. run `yarn link`
3. get the yarn link command generated as a result of step 2
4. go to this PR https://github.com/team-telnyx/webrtc-examples/pull/7
5. link the webrtc package there and see if the error was gone.
| Desktop     |![image](https://user-images.githubusercontent.com/16343871/192607287-585c7e8e-ac55-4788-8a9f-a85522e9e2ed.png)|
> fix(ENGDESK-19054): Voice SDK missing types when installed in TypeScript projects.

- packages/js/src/Modules/Verto/index.ts
- add `beforeunload` event to hang up active calls when the browser is closed or refreshed
1. Access webrtc.telnyx.com
2. Make a call 
3. After the callee picks up the call close the caller browser.
4. It should hang up the call on the callee side.
> feat(ENGDESK-21003): add beforeunload event to hang up active calls when the browser is closed or refreshed

- packages/react-client/package.json
- packages/react-client/src/TelnyxRTCProvider.tsx
- packages/react-client/src/useCallbacks.ts
- packages/react-client/src/useTelnyxRTC.ts
- yarn.lock
- Upgrade WebRTC library to support React 18
1. Navigate to  `packages/react-client`
2. Run yarn build
3. it should build without issues.
4. run yarn link
5. go to https://github.com/team-telnyx/webrtc-examples/pull/59
6. clone and install dependencies
7. run yarn link "@telnyx/react-client"
8. run the project and make a call
> feat(ENGDESK-27107): Upgrade WebRTC library to support React 18

- packages/js/rollup.config.js
- packages/js/src/Modules/Verto/messages/verto/BaseRequest.ts
- packages/js/src/Modules/Verto/webrtc/BaseCall.ts
- packages/js/src/Modules/Verto/webrtc/VertoHandler.ts
- packages/js/src/Modules/Verto/webrtc/interfaces.ts
- packages/js/src/utils/interfaces.ts
- add custom headers to invite and answer messages
1. navigate to `packages/js`
2. run `yarn build` and `yarn link`
3. go to a webrtc project example and run `yarn link @telnyx/webrtc`
4. go to `call.newCall({ customHeaders: [
{
name: 'X-INVITE-Call',
value: '9999999',
},
]})`
5. check if this customer header shows on `telnyx.rtc_invite` WS message.
6. go to `call.answer({
customHeaders: [
{
name: 'X-Answer-Call',
value: '9999999',
},
],
})`
7. check if this customer header shows on `telnyx.rtc_answer` WS message.
> feat(ENGDESK-26634): add custom headers to invite and answer messages

- packages/js/src/Modules/Verto/webrtc/BaseCall.ts
- the `params.customHeaders` was not destructuring correctly the values
1. navigate to `packages/js` 
2. run `yarn build`
3. run yarn link
4. go to a webrtc project and run the yarn link `@telnyx/webrtc`
5. make a call and receive a call
6. it should work normally.
> fix(ENGDESK-26634-hotfix): the `params.customHeaders` was not destructuring correctly the values

- packages/js/src/utils/interfaces.ts
Creating a client no longer requires `login_token`to be passed. This is to allow users to login with username and password without TypeScripts errors.
1. navigate to packages/js
2. run yarn build
3. run yarn link
4. go to a webrtc project and run the yarn link @telnyx/webrtc
5. This code should not throw typecheck errors.
```ts
const client = new TelnyxRTC({
login: "login",
password: "password"
})
```
> fix(ENGDESK-26922): Make `login_token` optional

- packages/js/src/Modules/Verto/webrtc/VertoHandler.ts
The `direction` is set to `Inbound` upon receiving an Invite message.
Not sure if this is the best approach. Feedback appreciated
WIP: tests.
> fix(ENGDESK-28811): call object direction is undefined upon receiving call

- packages/js/src/Modules/Verto/webrtc/BaseCall.ts
I added code to assign telnyx ids when the ringing event is received. 
Those ids are initially undefined because they are generated by the telephony engine, the `ringing` event is the first event that has these ids.
I couldn't check if `telnyxCallControlId` is set correctly, I'm new here, not sure how to test that manually
1. cd into js package
2. yarn build
3. yarn link
4. go to rtc-demo-2 (or any app for testing)
5. yarn link @telnyx/webrtc
6. initiate a call and inspect if telnyxIds are set properly
| Desktop     |     
|
> fix(ENGDESK-23349): bind telnyxids on ringing event for outbound calls

- packages/js/src/Modules/Verto/BrowserSession.ts
- packages/js/src/Modules/Verto/index.ts
- packages/js/src/Modules/Verto/util/constants/index.ts
- packages/js/src/Modules/Verto/util/helpers.ts
- packages/js/src/Modules/Verto/webrtc/BaseCall.ts
- packages/js/src/Modules/Verto/webrtc/Peer.ts
- Added calls to measure time between initiating a call and actually sending the invite
- Added utility to created deferred promises and debouncing functions
- Refactor Peer.ts, invite and answer calls to wait for ice gathering
> feat: add a faster work-around for ice gathering never completing

- packages/js/README.md
- packages/js/src/Modules/Verto/messages/WebRTCStatsMessage.ts
- packages/js/src/Modules/Verto/util/interfaces.ts
- packages/js/src/Modules/Verto/webrtc/BaseCall.ts
- packages/js/src/Modules/Verto/webrtc/Peer.ts
- packages/js/src/Modules/Verto/webrtc/VertoHandler.ts
- packages/js/src/Modules/Verto/webrtc/constants.ts
- packages/js/src/Modules/Verto/webrtc/interfaces.ts
> feat: implement debug output for file and websocket

- packages/js/src/Modules/Verto/webrtc/BaseCall.ts
- packages/js/src/Modules/Verto/webrtc/Peer.ts
- packages/js/src/Modules/Verto/webrtc/interfaces.ts
- packages/js/src/utils/interfaces.ts
[WEBRTC-2221](https://telnyx.atlassian.net/browse/WEBRTC-2221)
Allow setting preferred audio codec upon creating / answering a call 
[WEBRTC-2221]: https://telnyx.atlassian.net/browse/WEBRTC-2221?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: support caller codec preference

- packages/js/src/Modules/Verto/services/Connection.ts
- packages/js/src/Modules/Verto/util/reconnect.ts
[WEBRTC-2246](https://telnyx.atlassian.net/browse/WEBRTC-2246)
voice-sdk-proxy now returns a token used to re-establish ws connection to the b2bua-rtc instance in case the ws disconnects. 
this change saves the token to session storage and attaches it (if it exists) to the websocket host. 
[WEBRTC-2246]: https://telnyx.atlassian.net/browse/WEBRTC-2246?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: attach reconnection token to host

- packages/js/src/Modules/Verto/BaseSession.ts
The client should not terminate the socket connection. 
> fix: keep socket open for longer

- packages/js/src/Modules/Verto/index.ts
- packages/js/src/Modules/Verto/messages/verto/Login.ts
- packages/js/src/Modules/Verto/tests/messages.test.ts
[WEBRTC-2274](https://telnyx.atlassian.net/browse/WEBRTC-2274)
Add a boolean flag to the `Login` message to indicate whether the login is for a reconnection or not. 
[WEBRTC-2274]: https://telnyx.atlassian.net/browse/WEBRTC-2274?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: add reconnection flag to login message

- packages/js/src/Modules/Verto/BaseSession.ts
- packages/js/src/Modules/Verto/webrtc/Peer.ts
[WEBRTC-2307](https://telnyx.atlassian.net/browse/WEBRTC-2307)
[WEBRTC-2307]: https://telnyx.atlassian.net/browse/WEBRTC-2307?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: change reconnection logic

- .github/workflows/publish-gh-pages.yml
- packages/js/package.json
- packages/js/typedoc.html.json
[WEBRTC-2306](https://telnyx.atlassian.net/browse/WEBRTC-2306)
[WEBRTC-2306]: https://telnyx.atlassian.net/browse/WEBRTC-2306?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: publish generated docs to gh pages

- packages/js/src/Modules/Verto/util/interfaces.ts
- packages/js/src/Modules/Verto/webrtc/Peer.ts
- packages/js/src/Modules/Verto/webrtc/VertoHandler.ts
- packages/js/src/Modules/Verto/webrtc/interfaces.ts
- packages/js/src/TelnyxRTC.ts
- packages/js/src/utils/interfaces.ts
- packages/react-client/src/useTelnyxRTC.ts
> feat: add option to allow ice candidate prefetching

- packages/js/src/Modules/Verto/webrtc/Peer.ts
NO JIRA
Attach the event listener before adding the instance to be monitored. 
This fixes initial events that are not sent to the server. 
> fix: debug reports are missing initial events

- packages/js/src/Modules/Verto/webrtc/BaseCall.ts
Fixes WEBRTC-2443: Ringbacktone and ringtone not stopping properly after hang up
- Added `stopRingback()` call in the `hangup` function to ensure ringback tone is stopped when the call ends
- This complements the existing `stopRingtone()` call to ensure all audio is properly stopped
- Verified that ringback tone stops when call is hung up
- Tested both caller and callee hang up scenarios
- Fixes WEBRTC-2443
- This is a simple fix that ensures proper cleanup of audio resources
- No breaking changes introduced
> fix(webrtc): Stop ringback tone when call is hung up

- packages/js/src/Modules/Verto/services/Connection.ts
- packages/js/src/Modules/Verto/util/interfaces.ts
- packages/js/src/utils/interfaces.ts
Added a new client option to select which region of voice sdk proxy to connect to 
> feat: regional subdomains for voice-sdk

- packages/js/src/utils/interfaces.ts
addresses a bug introduced in v 2.22.12 where a typescript error is thrown when trying to resolve `Call` type from `interfaces.d.ts` this happens if you have path aliases configured in typescript to resolve `src/**/*`
> fix: export Call via relative path

- .github/workflows/update-changelog.yaml
[ENGDESK-44117](https://telnyx.atlassian.net/browse/ENGDESK-44117)
concat CHANGELOG.md entries to the beginning of the file
[ENGDESK-44117]: https://telnyx.atlassian.net/browse/ENGDESK-44117?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: concat new changelog entries to the beginning of file

- .github/workflows/draft-release.yml
- .github/workflows/publish-release.yml
- .github/workflows/update-changelog.yaml
- make sure to bump correct version when prerelease is used
> chore: update workflows for prerelease bumps
